apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-regel-api
  namespace: dp
  labels:
    team: teamdagpenger
spec:
  image: repo.adeo.no:5443/dp-regel-api:latest
  port: 8092
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
  env:
  - name: REDIS_HOST
    value: dp-regel-api-redis.dp.svc.nais.local
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: d26apvl00159.test.local:8443,d26apvl00160.test.local:8443,d26apvl00161.test.local:8443
  ingresses:
    - "https://dp-regel-api-dp.nais.preprod.local"
